[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[redirects]]
  from = "https://zcip-reading-list.netlify.app"
  to = "https://reading-list.zcip.dev"
  status = 301
  force = true